<?xml version="1.0" encoding="UTF-8"?>
<!--
/*********************************************************************
* Copyright (c) 2024 Contributors to the Eclipse Foundation.
*
* This program and the accompanying materials are made
* available under the terms of the Eclipse Public License 2.0
* which is available at https://www.eclipse.org/legal/epl-2.0/
*
* SPDX-License-Identifier: EPL-2.0
**********************************************************************/
-->
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="rolapmapping" nsURI="https://www.daanse.org/spec/org.eclipse.daanse.rolap.mapping"
    nsPrefix="roma">
  <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
    <details key="qualified" value="true"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Documentation" eSuperTypes="#//IDocumentation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Annotation" eSuperTypes="#//IAnnotation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractElement" abstract="true" eSuperTypes="#//IAbstractElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="annotations" upperBound="-1"
        eType="#//Annotation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="documentation" eType="#//Documentation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Catalog" eSuperTypes="#//AbstractElement #//ICatalog">
    <eStructuralFeatures xsi:type="ecore:EReference" name="schemas" upperBound="-1"
        eType="#//Schema" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cubes" upperBound="-1"
        eType="#//Cube" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dimensions" upperBound="-1"
        eType="#//Dimension" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hierarchies" upperBound="-1"
        eType="#//Hierarchy" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="levels" upperBound="-1"
        eType="#//Level" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="formatters" upperBound="-1"
        eType="#//Formatter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="measures" upperBound="-1"
        eType="#//Measure" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="accessRoles" upperBound="-1"
        eType="#//AccessRole" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregationTables" upperBound="-1"
        eType="#//AggregationTable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregationExcludes" upperBound="-1"
        eType="#//AggregationExclude" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dbschermas" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Schema" eSuperTypes="#//ISchema #//AbstractElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cubes" lowerBound="1" upperBound="-1"
        eType="#//Cube"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="namedSets" upperBound="-1"
        eType="#//NamedSet"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="accessRoles" upperBound="-1"
        eType="#//AccessRole"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="measuresDimensionName"
        ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultAccessRole" eType="#//AccessRole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cube" abstract="true" eSuperTypes="#//AbstractElement #//ICube">
    <eStructuralFeatures xsi:type="ecore:EReference" name="calculatedMembers" upperBound="-1"
        eType="#//CalculatedMember" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="namedSets" upperBound="-1"
        eType="#//NamedSet" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="kpis" upperBound="-1" eType="#//Kpi"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabled" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visible" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="measureGroups" upperBound="-1"
        eType="#//MeasureGroup" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultMeasure" eType="#//Measure"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PhysicalCube" eSuperTypes="#//Cube #//IPhysicalCube">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dimensionConnectors" upperBound="-1"
        eType="#//DimensionConnector" containment="true" eOpposite="#//DimensionConnector/physicalCube"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="query" lowerBound="1" eType="#//Query"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="writebackTable" eType="#//WritebackTable"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" upperBound="-1"
        eType="#//Action" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cache" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VirtualCube" eSuperTypes="#//Cube #//IVirtualCube">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dimensionConnectors" upperBound="-1"
        eType="#//DimensionConnector"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cubeUsages" lowerBound="1"
        upperBound="-1" eType="#//CubeConnector" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CubeConnector" eSuperTypes="#//ICubeConnector">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ignoreUnrelatedDimensions"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cube" lowerBound="1" eType="#//Cube"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MeasureGroup" eSuperTypes="#//IMeasureGroup">
    <eStructuralFeatures xsi:type="ecore:EReference" name="measures" lowerBound="1"
        upperBound="-1" eType="#//Measure"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Measure" eSuperTypes="#//AbstractElement #//IMeasure">
    <eOperations name="getDatatype" lowerBound="1" eType="#//DataType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel"/>
    </eOperations>
    <eOperations name="getAggregatorType" lowerBound="1" eType="#//MeasureAggregatorType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="measureExpression" eType="#//SQLExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="calculatedMemberProperty"
        upperBound="-1" eType="#//CalculatedMemberProperty" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cellFormatter" eType="#//CellFormatter"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="backColor" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="column" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataType" eType="#//ColumnDataType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayFolder" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="formatString" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="formatter" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visible" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aggregator" eType="#//MeasureAggregator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Kpi" eSuperTypes="#//AbstractElement #//IKpi">
    <eStructuralFeatures xsi:type="ecore:EReference" name="translations" upperBound="-1"
        eType="#//Translation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayFolder" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="associatedMeasureGroupID"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="goal" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="trend" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weight" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="trendGraphic" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="statusGraphic" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentTimeMember" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parentKpiID" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedSet" eSuperTypes="#//AbstractElement #//INamedSet">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayFolder" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="formula" eType="#//Formula"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dimension" abstract="true" eSuperTypes="#//AbstractElement #//IDimension">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hierarchies" lowerBound="1"
        upperBound="-1" eType="#//Hierarchy"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="usagePrefix" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visible" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DimensionConnector" eSuperTypes="#//IDimensionConnector">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="foreignKey" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="usagePrefix" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visible" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dimension" lowerBound="1"
        eType="#//Dimension"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="overrideDimensionName"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level" eType="#//Level"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="physicalCube" lowerBound="1"
        eType="#//PhysicalCube" eOpposite="#//PhysicalCube/dimensionConnectors"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimeDimension" eSuperTypes="#//Dimension #//ITimeDimension"/>
  <eClassifiers xsi:type="ecore:EClass" name="StandardDimension" eSuperTypes="#//Dimension #//IStandardDimension"/>
  <eClassifiers xsi:type="ecore:EClass" name="Hierarchy" eSuperTypes="#//AbstractElement #//IHierarchy">
    <eStructuralFeatures xsi:type="ecore:EReference" name="levels" lowerBound="1"
        upperBound="-1" eType="#//Level"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="memberReaderParameters"
        upperBound="-1" eType="#//MemberReaderParameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="allLevelName" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="allMemberCaption" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="allMemberName" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultMember" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayFolder" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasAll" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="memberReaderClass" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="origin" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="primaryKey" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="primaryKeyTable" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uniqueKeyLevelName" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visible" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="query" eType="#//Query"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Level" eSuperTypes="#//ILevel #//AbstractElement">
    <eOperations name="getDataType" lowerBound="1" eType="#//DataType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return null; // code here"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getHideMemberIfType" lowerBound="1" eType="#//HideMemberIfType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return null; // code here"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getLevelType" lowerBound="1" eType="#//LevelType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return null; // code here"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="keyExpression" eType="#//SQLExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nameExpression" eType="#//SQLExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="captionExpression" eType="#//SQLExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ordinalExpression" eType="#//SQLExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentExpression" eType="#//SQLExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentChildLink" eType="#//ParentChildLink"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="memberProperties" upperBound="-1"
        eType="#//MemberProperty" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="memberFormatter" eType="#//MemberFormatter"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="approxRowCount" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="captionColumn" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="column" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hideMemberIf" eType="#//HideMemberIf"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//LevelDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nameColumn" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nullParentValue" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ordinalColumn" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parentColumn" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="table" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="columnType" eType="#//ColumnDataType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uniqueMembers" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visible" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MemberProperty" eSuperTypes="#//AbstractElement #//IMemberProperty">
    <eOperations name="getDataType" lowerBound="1" eType="#//DataType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return null; // code here"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="formatter" eType="#//MemberPropertyFormatter"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="column" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dependsOnLevelValue" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="propertyType" eType="#//ColumnDataType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CalculatedMember" eSuperTypes="#//AbstractElement #//ICalculatedMember">
    <eStructuralFeatures xsi:type="ecore:EReference" name="calculatedMemberProperties"
        upperBound="-1" eType="#//CalculatedMemberProperty" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cellFormatter" eType="#//CellFormatter"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="formula" eType="#//Formula"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayFolder" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="formatString" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parent" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visible" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hierarchy" eType="#//Hierarchy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CalculatedMemberProperty" eSuperTypes="#//AbstractElement #//ICalculatedMemberProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParentChildLink" eSuperTypes="#//IParentChildLink">
    <eStructuralFeatures xsi:type="ecore:EReference" name="table" lowerBound="1" eType="#//TableQuery"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="childColumn" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parentColumn" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SQLExpression" eSuperTypes="#//ISQLExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sqls" lowerBound="1" upperBound="-1"
        eType="#//SQL" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Query" abstract="true" eSuperTypes="#//IQuery"/>
  <eClassifiers xsi:type="ecore:EClass" name="RelationalQuery" abstract="true" eSuperTypes="#//Query #//IRelationalQuery">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alias" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InlineTableQuery" eSuperTypes="#//RelationalQuery #//IInlineTableQuery">
    <eStructuralFeatures xsi:type="ecore:EReference" name="columnDefinitions" upperBound="-1"
        eType="#//InlineTableColumnDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rows" lowerBound="1" upperBound="-1"
        eType="#//InlineTableRow" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InlineTableColumnDefinition" eSuperTypes="#//IInlineTableColumnDefinition">
    <eOperations name="getDataType" lowerBound="1" eType="#//DataType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return null; // code here"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ColumnDataType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InlineTableRow" eSuperTypes="#//IInlineTableRow">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cells" lowerBound="1" upperBound="-1"
        eType="#//InlineTableRowCell" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InlineTableRowCell" eSuperTypes="#//IInlineTableRowCell">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="columnName" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JoinQuery" eSuperTypes="#//Query #//IJoinQuery">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1" eType="#//JoinedQueryElement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1" eType="#//JoinedQueryElement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JoinedQueryElement" eSuperTypes="#//IJoinedQueryElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alias" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="query" lowerBound="1" eType="#//Query"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SQL" eSuperTypes="#//ISQL">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dialects" lowerBound="1"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="statement" lowerBound="1"
        eType="#//SQLStatement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="SQLStatement" instanceClassName="java.lang.String"/>
  <eClassifiers xsi:type="ecore:EClass" name="TableQuery" eSuperTypes="#//RelationalQuery #//ITableQuery">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sqlWhereExpression" eType="#//SQL"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregationExcludes" upperBound="-1"
        eType="#//AggregationExclude" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="optimizationHints" upperBound="-1"
        eType="#//TableQueryOptimizationHint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="schema" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregationTables" upperBound="-1"
        eType="#//AggregationTable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableQueryOptimizationHint" eSuperTypes="#//ITableQueryOptimizationHint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SqlSelectQuery" eSuperTypes="#//RelationalQuery #//ISqlSelectQuery">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sQL" lowerBound="1" upperBound="-1"
        eType="#//SQL" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MemberReaderParameter" eSuperTypes="#//IMemberReaderParameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Translation" eSuperTypes="#//ITranslation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="language" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//UnsignedInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="caption" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayFolder" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="annotations" upperBound="-1"
        eType="#//Annotation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Formula" instanceClassName="java.lang.String"/>
  <eClassifiers xsi:type="ecore:EClass" name="Formatter" abstract="true" eSuperTypes="#//AbstractElement #//IFormatter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ref" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CellFormatter" eSuperTypes="#//Formatter #//ICellFormatter"/>
  <eClassifiers xsi:type="ecore:EClass" name="MemberFormatter" eSuperTypes="#//Formatter #//IMemberFormatter"/>
  <eClassifiers xsi:type="ecore:EClass" name="MemberPropertyFormatter" eSuperTypes="#//Formatter #//IMemberPropertyFormatter"/>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="#//IParameter">
    <eOperations name="getType" eType="#//DataType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return null; // code here"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modifiable" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataType" lowerBound="1"
        eType="#//ColumnDataType" defaultValueLiteral="String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action" eSuperTypes="#//AbstractElement #//IAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="DrillThroughAction" eSuperTypes="#//Action #//IDrillThroughAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="drillThroughAttribute"
        upperBound="-1" eType="#//DrillThroughAttribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="drillThroughMeasure" upperBound="-1"
        eType="#//Measure" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="default" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DrillThroughAttribute" eSuperTypes="#//IDrillThroughAttribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="property" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dimension" lowerBound="1"
        eType="#//Dimension"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hierarchy" eType="#//Hierarchy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level" eType="#//Level"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WritebackAttribute" eSuperTypes="#//IWritebackAttribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="column" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dimension" lowerBound="1"
        eType="#//Dimension"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WritebackMeasure" eSuperTypes="#//IWritebackMeasure">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="column" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WritebackTable" eSuperTypes="#//IWritebackTable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="writebackAttribute" upperBound="-1"
        eType="#//WritebackAttribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="writebackMeasure" upperBound="-1"
        eType="#//WritebackMeasure" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="schema" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AggregationExclude" eSuperTypes="#//IAggregationExclude">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ignorecase" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pattern" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AggregationForeignKey" eSuperTypes="#//IAggregationForeignKey">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aggregationColumn" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="factColumn" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AggregationLevel" eSuperTypes="#//IAggregationLevel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregationLevelProperties"
        upperBound="-1" eType="#//AggregationLevelProperty" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="captionColumn" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="collapsed" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="column" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nameColumn" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ordinalColumn" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AggregationLevelProperty" eSuperTypes="#//IAggregationLevelProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="column" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AggregationMeasure" eSuperTypes="#//IAggregationMeasure">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="column" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rollupType" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AggregationMeasureFactCount" eSuperTypes="#//IAggregationMeasureFactCount">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="column" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="factColumn" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AggregationTable" abstract="true" eSuperTypes="#//IAggregationTable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregationFactCount" lowerBound="1"
        eType="#//AggregationColumnName" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregationIgnoreColumns"
        upperBound="-1" eType="#//AggregationColumnName" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregationForeignKeys"
        upperBound="-1" eType="#//AggregationForeignKey" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregationMeasures" lowerBound="1"
        upperBound="-1" eType="#//AggregationMeasure" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregationLevels" upperBound="-1"
        eType="#//AggregationLevel" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregationMeasureFactCounts"
        upperBound="-1" eType="#//AggregationMeasureFactCount" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ignorecase" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AggregationName" eSuperTypes="#//AggregationTable #//IAggregationName">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="approxRowCount" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AggregationPattern" eSuperTypes="#//AggregationTable #//IAggregationPattern">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pattern" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="excludes" upperBound="-1"
        eType="#//AggregationExclude"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AggregationColumnName" eSuperTypes="#//IAggregationColumnName">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="column" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AccessCubeGrant" eSuperTypes="#//IAccessCubeGrant">
    <eOperations name="getAccess" lowerBound="1" eType="#//AccessCube">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return null; // Code here"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dimensionGrants" upperBound="-1"
        eType="#//AccessDimensionGrant" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hierarchyGrants" upperBound="-1"
        eType="#//AccessHierarchyGrant" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cubeAccess" lowerBound="1"
        eType="#//CubeAccess"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cube" lowerBound="1" eType="#//Cube"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AccessDimensionGrant" eSuperTypes="#//IAccessDimensionGrant">
    <eOperations name="getAccess" lowerBound="1" eType="#//AccessDimension">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return null; // Code here"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dimensionAccess" lowerBound="1"
        eType="#//DimensionAccess"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dimension" lowerBound="1"
        eType="#//Dimension"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AccessHierarchyGrant" eSuperTypes="#//IAccessHierarchyGrant">
    <eOperations name="getAccess" lowerBound="1" eType="#//AccessHierarchy">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return null; // Code here"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getRollupPolicyType" lowerBound="1" eType="#//RollupPolicyType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return null; //code here"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="memberGrants" upperBound="-1"
        eType="#//AccessMemberGrant" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hierarchyAccess" lowerBound="1"
        eType="#//HierarchyAccess"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rollupPolicy" lowerBound="1"
        eType="#//RollupPolicy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hierarchy" lowerBound="1"
        eType="#//Hierarchy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bottomLevel" eType="#//Level"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="topLevel" eType="#//Level"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AccessMemberGrant" eSuperTypes="#//IAccessMemberGrant">
    <eOperations name="getAccess" lowerBound="1" eType="#//AccessMember">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return null; // Code here"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="memberAccess" lowerBound="1"
        eType="#//MemberAccess"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="member" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AccessRole" eSuperTypes="#//AbstractElement #//IAccessRole">
    <eStructuralFeatures xsi:type="ecore:EReference" name="accessSchemaGrants" upperBound="-1"
        eType="#//AccessSchemaGrant" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencedAccessRoles"
        upperBound="-1" eType="#//AccessRole" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AccessSchemaGrant" eSuperTypes="#//IAccessSchemaGrant">
    <eOperations name="getAccess" lowerBound="1" eType="#//AccessSchema">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return null; // Code here"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cubeGrants" lowerBound="1"
        upperBound="-1" eType="#//AccessCubeGrant" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="schemaAccess" lowerBound="1"
        eType="#//SchemaAccess"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IAbstractElement" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.AbstractElementMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IAccessCubeGrant" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.AccessCubeGrantMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IAccessDimensionGrant" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.AccessDimensionGrantMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IAccessHierarchyGrant" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.AccessHierarchyGrantMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IAccessMemberGrant" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.AccessMemberGrantMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IAccessRole" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.AccessRoleMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IAccessSchemaGrant" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.AccessSchemaGrantMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IAction" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.ActionMappingMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IAggregationColumnName" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.AggregationColumnNameMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IAggregationExclude" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.AggregationExcludeMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IAggregationForeignKey" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.AggregationForeignKeyMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IAggregationLevel" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.AggregationLevelMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IAggregationLevelProperty" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.AggregationLevelPropertyMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IAggregationMeasureFactCount" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.AggregationMeasureFactCountMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IAggregationMeasure" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.AggregationMeasureMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IAggregationName" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.AggregationNameMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IAggregationPattern" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.AggregationPatternMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IAggregationTable" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.AggregationTableMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IAnnotation" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.AnnotationMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ICalculatedMember" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.CalculatedMemberMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ICalculatedMemberProperty" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.CalculatedMemberPropertyMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ICatalog" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.CatalogMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ICellFormatter" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.CellFormatterMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ICubeConnector" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.CubeConnectorMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ICube" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.CubeMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IDimensionConnector" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.DimensionConnectorMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IDimension" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.DimensionMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IDocumentation" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.DocumentationMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IDrillThroughAction" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.DrillThroughActionMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IDrillThroughAttribute" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.DrillThroughAttributeMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IFormatter" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.FormatterMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IHierarchy" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.HierarchyMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IInlineTableColumnDefinition" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.InlineTableColumnDefinitionMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IInlineTableQuery" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.InlineTableQueryMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IInlineTableRowCell" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.InlineTableRowCellMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IInlineTableRow" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.InlineTableRowMappingMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IJoinedQueryElement" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.JoinedQueryElementMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IJoinQuery" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.JoinQueryMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IKpi" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.KpiMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ILevel" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.LevelMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IMeasureGroup" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.MeasureGroupMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IMeasure" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.MeasureMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IMemberProperty" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.MemberPropertyMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IMemberPropertyFormatter" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.MemberPropertyFormatterMapping"
      abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IMemberFormatter" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.MemberFormatterMapping"
      abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IMemberReaderParameter" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.MemberReaderParameterMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="INamedSet" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.NamedSetMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IParameter" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.ParameterMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IParentChildLink" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.ParentChildLinkMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IPhysicalCube" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.PhysicalCubeMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IQuery" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.QueryMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IRelationalQuery" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.RelationalQueryMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ISchema" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.SchemaMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ISQLExpression" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.SQLExpressionMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ISQL" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.SQLMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ISqlSelectQuery" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.SqlSelectQueryMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IStandardDimension" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.StandardDimensionMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ITableQuery" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.TableQueryMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ITableQueryOptimizationHint" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.TableQueryOptimizationHintMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ITimeDimension" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.TimeDimensionMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ITranslation" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.TranslationMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IVirtualCube" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.VirtualCubeMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IWritebackAttribute" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.WritebackAttributeMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IWritebackMeasure" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.WritebackMeasureMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IWritebackTable" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.WritebackTableMapping"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="SchemaAccess">
    <eLiterals name="NONE" literal="none"/>
    <eLiterals name="ALL" value="1" literal="all"/>
    <eLiterals name="CUSTOM" value="2" literal="custom"/>
    <eLiterals name="ALL_DIMENSIONS" value="3" literal="all_dimensions"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CubeAccess">
    <eLiterals name="NONE" literal="none"/>
    <eLiterals name="ALL" value="1" literal="all"/>
    <eLiterals name="CUSTOM" value="2" literal="custom"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DimensionAccess">
    <eLiterals name="NONE" literal="none"/>
    <eLiterals name="ALL" value="1" literal="all"/>
    <eLiterals name="CUSTOM" value="2" literal="custom"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="HierarchyAccess">
    <eLiterals name="NONE" literal="none"/>
    <eLiterals name="ALL" value="1" literal="all"/>
    <eLiterals name="CUSTOM" value="2" literal="custom"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="HideMemberIf">
    <eLiterals name="NEVER" literal="never"/>
    <eLiterals name="IF_BLANK_NAME" value="1" literal="IfBlankName"/>
    <eLiterals name="IF_PARENTS_NAME" value="2" literal="IfParentsName"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MemberAccess">
    <eLiterals name="NONE" literal="none"/>
    <eLiterals name="ALL" value="1" literal="all"/>
    <eLiterals name="CUSTOM" value="2" literal="custom"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RollupPolicy">
    <eLiterals name="FULL" literal="full"/>
    <eLiterals name="PARTIAL" value="1" literal="partial"/>
    <eLiterals name="HIDDEN" value="3" literal="hidden"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MeasureAggregator">
    <eLiterals name="SUM" literal="sum"/>
    <eLiterals name="COUNT" value="1" literal="count"/>
    <eLiterals name="MIN" value="2" literal="min"/>
    <eLiterals name="MAX" value="3" literal="max"/>
    <eLiterals name="AVG" value="4" literal="avg"/>
    <eLiterals name="DICTINCT_COUNT" value="5" literal="distinct-count"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ColumnDataType">
    <eLiterals name="AUTO" literal="auto"/>
    <eLiterals name="STRING" value="1" literal=" String"/>
    <eLiterals name="NUMERIC" value="2" literal="Numeric"/>
    <eLiterals name="INTEGER" value="3" literal="Integer"/>
    <eLiterals name="BOOLEAN" value="4" literal="Boolean"/>
    <eLiterals name="DATE" value="5" literal="Date"/>
    <eLiterals name="TIME" value="6" literal="Time"/>
    <eLiterals name="TIMESTAMP" value="7" literal="Timestamp"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LevelDefinition">
    <eLiterals name="REGULAR" literal="Regular">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Indicates that the level is not related to time."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="TIME_YEARS" literal="TimeYears">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Indicates that a level refers to years."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="TIME_HALF_YEARS" literal="TimeHalfYears">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Indicates that a level refers to half years"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="TIME_QUARTERS" literal="TimeQuarters">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Indicates that a level refers to quarters"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="TIME_MONTHS" literal="TimeMonths">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Indicates that a level refers to months"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="TIME_WEEKS" literal="TimeWeeks">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Indicates that a level refers to weeks"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="TIME_DAYS" literal="TimeDays">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Indicates that a level refers to days"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="TIME_HOURS" literal="TimeHours">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Indicates that a level refers to hours"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="TIME_MINUTES" literal="TimeMinutes">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Indicates that a level refers to minutes"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="TIME_SECONDS" literal="TimeSeconds">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Indicates that a level refers to seconds"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="TIME_UNDEFINED" literal="TimeUndefined">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Indicates that a level is an unspecified time period"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="NULL" literal="Null">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Indicates that a level holds the null member"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="GEO_CONTINENT" literal="GeographicContinent">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Indicates that a level holds the geographical object Continent."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="GEO_REGION" literal="GeographicRegion">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Indicates that a level holds the geographical object Region."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="GEO_COUNTRY" literal="GeographicCountry">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Indicates that a level holds the geographical object Country."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="GEO_STATE_OR_PROVINCE" literal="GeographicProvince">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Indicates that a level holds the geographical objects State or Province."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="GEO_COUNTY" literal="GeographicCounty">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Indicates that a level holds the geographical object County."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="GEO_CITY" literal="GeographicCity">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Indicates that a level holds the geographical object City."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="GEO_POSTALCODE" literal="GeographicPostalCode">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Indicates that a level holds the geographical object PostalCode."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="GEO_POINT" literal="GeographicPoint">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Indicates that a level holds the geographical object Point."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="ORG_UNIT" literal="OrganisationUnit">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Indicates that a level holds a OrganisationUnit."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="BOM_RESOURCE" literal="BomResource">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Indicates that a level holds a Bom Resource."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="QUANTITATIVE" literal="Quantitative">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Indicates that a level is a QUANTITATIVE."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="ACCOUNT" literal="Account">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Indicates that a level is a Account."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="CUSTOMER" literal="Customer">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Indicates that a level is a Customer."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="CUSTOMER_GROUP" literal="CustomerGroup">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Indicates that a level is a CustomerGroup."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="CUSTOMER_HOUSEHOLD" literal="CustomerHouseHold">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Indicates that a level is a CustomerGroup."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="PRODUCT" literal="Product">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Indicates that a level is a Product."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="PRODUCT_GROUP" literal="ProductGroup">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Indicates that a level is a ProductGroup."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="SCENARIO" literal="Scenario">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Indicates that a level is a Scenario."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="UTILITY" literal="Utility">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Indicates that a level is a Utility."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="PERSON" literal="Person">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Indicates that a level is a Person."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="COMPANY" literal="Company">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Indicates that a level is a Company."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="CURRENCY_SOURCE" literal="CurrencySource">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Indicates that a level is a CurrencySource."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="CURRENCY_DESTINATION" literal="CurrencyDestination">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Indicates that a level is a CurrencyDestination."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="CHANNEL" literal="Channel">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Indicates that a level is a Channel."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="REPRESENTATIVE" literal="Representative">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Indicates that a level is a Representative."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="PROMOTION" literal="Promotion">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Indicates that a level is a Promotion."/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AccessSchema" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.enums.AccessSchema"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AccessCube" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.enums.AccessCube"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AccessDimension" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.enums.AccessDimension"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AccessHierarchy" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.enums.AccessHierarchy"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AccessMember" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.enums.AccessMember"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DataType" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.enums.DataType"/>
  <eClassifiers xsi:type="ecore:EDataType" name="HideMemberIfType" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.enums.HideMemberIfType"/>
  <eClassifiers xsi:type="ecore:EDataType" name="LevelType" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.enums.LevelType"/>
  <eClassifiers xsi:type="ecore:EDataType" name="RollupPolicyType" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.enums.RollupPolicyType"/>
  <eClassifiers xsi:type="ecore:EDataType" name="MeasureAggregatorType" instanceClassName="org.eclipse.daanse.rolap.mapping.api.model.enums.MeasureAggregatorType"/>
</ecore:EPackage>
